lost-and-found/accounts/urls.py
from django.urls import path
from .views import SignupView, LoginView, logout_view, ProfileView, MyPostView, ChangePasswordView, EditProfileView

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'), # SignupView
    path('login/', LoginView.as_view(), name='login'), # LoginView
    path('<int:user_id>/', ProfileView.as_view(), name='profile'), # ProfileView
    path('my_posts/', MyPostView.as_view(), name='my_posts'),# myposts
    path('logout/', logout_view, name='logout'), # logout
    path('change_password/', ChangePasswordView.as_view(), name='change_password'), # Change Password
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile')
]

lost-and-found/chats/urls.py
from django.urls import path
from .views import ChatIndexView, ChatAPI, MessageAPI

urlpatterns = [
    path('', ChatIndexView.as_view(), name='chat_index'),
    path('chat_api/', ChatAPI.as_view(), name='chat_api'),
    path('message_api/<int:user_id>/', MessageAPI.as_view(), name='message_api')
]

lost-and-found/lost-and-found/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('chats/', include('chats.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lost-and-found/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# accounts app

# Create your models here.

class Faculty(models.Model):
    faculty_name = models.CharField(max_length=255)

    def __str__(self):
        return self.faculty_name

class UserProfile(models.Model):
    avatar = models.ImageField(default='accounts/user_default.gif', upload_to='accounts/') # Picture of user
    user = models.OneToOneField(User, on_delete=models.CASCADE) # reference to User Table
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE) # reference to Faculty Table

    def __str__(self):
        return self.user.username

lost-and-found/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# posts app

# Create your models here.


class AssetType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):
    is_active = models.BooleanField(default=True)
    TYPE = (
        ('found', 'เจอของหาย'),
        ('lost', 'ตามหาของ'),
    )
    type = models.CharField(choices=TYPE, max_length=255, default='found')
    date_time = models.DateTimeField()
    create_at = models.DateTimeField(auto_now_add=True)
    desc = models.TextField()
    title = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    contact1 = models.CharField(max_length=255)
    contact2 = models.CharField(max_length=255)
    key = models.CharField(max_length=255, unique=True, null=True, blank=True)
    assetType = models.ForeignKey(AssetType, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    # for closed post
    take_information = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.title

class PostPicture(models.Model):
    picture = models.ImageField(default='posts/post_default.gif', upload_to='posts/')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

class Comment(models.Model):
    msg = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.msg

lost-and-found/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django import forms
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):

    username = forms.CharField(
        widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'ชื่อผู้ใช้งาน'}),
        label = 'ชื่อผู้ใช้งาน'
    )
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ชื่อจริง'}),
        max_length=32,
        label = 'ชื่อจริง'

    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'นามสกุล'}),
        max_length=32,
        label='นามสกุล'
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'example@example.com'}),
        max_length=64,
        label='อีเมล์'
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'รหัสผ่าน'}),
        label='รหัสผ่าน'
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'ยืนยันรหัสผ่าน'}),
        label='ยืนยันรหัสผ่าน'
    )
    class Meta:
        model = User
        fields = ("username", "password1", "password2", "first_name", "last_name", "email")

class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'รหัสผ่านเก่า'}),
        label='รหัสผ่านเก่า'
    )

    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'รหัสผ่านใหม่'}),
        label='รหัสผ่านใหม่'
    )

    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'ยืนยันรหัสผ่าน'}),
        label='ยืนยันรหัสผ่าน'
    )

class EditProfileForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ชื่อจริง'}),
        max_length=32,
        label = 'ชื่อจริง'
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'นามสกุล'}),
        max_length=32,
        label='นามสกุล'
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'example@example.com'}),
        max_length=64,
        label='อีเมล์'
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

lost-and-found/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignupForm, MyPasswordChangeForm, EditProfileForm
from .models import Faculty, UserProfile
from posts.models import Post
from chats.models import Chat
from django.contrib.auth.models import User
from django.views import View

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.


class SignupView(View):
    template_name = 'signup.html'

    def get(self, request):
        form = SignupForm()
        return render(request, self.template_name, {
            'form': form,
            'facultys': Faculty.objects.all()
        })

    def post(self, request):
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            faculty = Faculty.objects.get(
                id=request.POST.get('faculty')
            )

            try:
                picture = request.FILES['picture']
            except:
                picture = None

            userprofile = UserProfile.objects.create(
                user=user,
                faculty=faculty
            )

            if picture != None:
                userprofile.avatar = picture
                userprofile.save()

            Chat.objects.create(
                user=user
            )
            # login
            login(request, user)
            return redirect('index')
        else:
            return render(request, self.template_name, {
                'form': form,
                'facultys': Faculty.objects.all()
            })


class LoginView(View):
    template_name = 'login.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('index')
        # if have next send it to save in input:hidden
        next_url = request.GET.get('next')
        return render(request, 'login.html', {
            'next_url': next_url
        })

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        next_url = request.POST.get('next_url')
        if user:
            login(request, user)
            if next_url != 'None':
                return redirect(next_url)
            else:
                return redirect('index')

        return render(request, 'login.html', {
            'next_url': next_url,
            'error': 'ชื่อผู้ใช้งานหรือรหัสผ่านไม่ถูกต้อง'
        })


class MyPostView(View):
    template_name = 'my_posts.html'

    def get(self, request):
        if request.user.is_authenticated:
            posts = Post.objects.filter(user=request.user).order_by(
                '-is_active', '-create_at')
            founds = Post.objects.filter(user=request.user, type='found')
            losts = Post.objects.filter(user=request.user, type='lost')
        else:
            posts = "key"
            founds = []
            losts = []
        return render(request, self.template_name, {
            'posts': posts,
            'founds': founds,
            'losts': losts,
            'closed': len(Post.objects.filter(user=request.user, is_active=False)) if request.user.is_authenticated else len(Post.objects.filter(is_active=False))
        })

    def post(self, request):
        key = request.POST.get('key')
        try:
            post = Post.objects.get(key=key)
            return render(request, self.template_name, {
                'posts': [post],
                'key': key
            })
        except:
            return render(request, self.template_name, {
                'posts': 'key',
                'key_error': 'ไม่มีโพสต์นี้ในระบบ'
            })


class ProfileView(View):
    template_name = 'profile.html'

    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        posts = Post.objects.filter(user=user)
        founds = Post.objects.filter(user=user, type='found')
        losts = Post.objects.filter(user=user, type='lost')
        closed = 0
        for post in posts:
            if post.is_active == False:
                closed += 1
        context = {
            'user': user,
            'posts': posts,
            'closed': closed,
            'active': len(posts) - closed,
            'founds': founds,
            'losts': losts
        }
        return render(request, self.template_name, context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('index')


@method_decorator(login_required, name='dispatch')
class ChangePasswordView(View):
    template_name = 'change_password.html'

    def get(self, request):
        user = request.user
        form = MyPasswordChangeForm(user=user)

        return render(request, self.template_name, {
            'user': user,
            'form': form
        })

    def post(self, request):
        user = request.user
        form = MyPasswordChangeForm(data=request.POST, user=user)

        if form.is_valid():
            form.save()
            return redirect('login')
        else:
            return render(request, self.template_name, {
                'user': user,
                'form': form
            })


@method_decorator(login_required, name='dispatch')
class EditProfileView(View):
    template_name = 'edit_profile.html'

    def get(self, request):
        user = request.user
        form = EditProfileForm(instance=user)
        faculty = Faculty.objects.all()

        return render(request, self.template_name, {
            'user': user,
            'form': form,
            'facultys': faculty
        })

    def post(self, request):
        user = request.user
        userprofile = UserProfile.objects.get(user=user)
        form = EditProfileForm(request.POST, instance=user)

        userprofile.faculty = Faculty.objects.get(
            id=int(request.POST.get('faculty')))

        userprofile.save()

        try:
            picture = request.FILES['picture']
        except:
            picture = None

        if picture != None:
            userprofile.avatar = picture
            userprofile.save()

        if form.is_valid():
            form.save()
            return render(request, self.template_name, {
                'user': user,
                'form': form,
                'facultys': Faculty.objects.all(),
                'success': 'แก้ไขโปรไฟล์เรียบร้อยแล้ว'
            })
        else:
            return render(request, self.template_name, {
                'user': user,
                'form': form,
                'facultys': Faculty.objects.all()
            })

lost-and-found/accounts/templates/change_password.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}
    Lost & Found : เปลี่ยนรหัสผ่าน
{% endblock %}

{% block style %}
    <style>
        .errorlist{
            margin-left: 3em;
            margin-top: 1em;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4 text-center border-right p-5">
                <img src="{% static 'images/lost&found.png'%}" alt="" width='100%' class='rotate-img'>
            </div>
            <div class="col-md ml-5">

                <h1 class='mb-5'><b>เปลี่ยนรหัสผ่าน <i class="fas fa-key"></i></b> </h1>
                <form method="POST" action="{% url 'change_password' %}" class='mt-3'>
                    {% csrf_token %}
                    {% for each_form in form %}
                        <div class="form-group mb-3">
                            <label for="{{ each_form.id_for_label }}">{{ each_form.label }}</label>
                            <div class="input-group">
                                {{ each_form }}
                                <div class="input-group-append" id='password_see{{ forloop.counter }}' style='cursor: pointer;'>
                                    <span class="input-group-text">
                                        <i id='password_eye{{ forloop.counter }}' class="fas fa-eye-slash"></i>
                                    </span>
                                </div>
                            </div>
                            <small class='text-danger'> {{ each_form.errors.0 }} </small>
                        </div>
                    {% endfor %}

                    <input type="hidden" name="next_url" value='{{ next_url }}'>
                    <button type="submit" class='btn btn-primary mt-3'>เปลี่ยนรหัสผ่าน</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        $('#password_see1').click(function(){
            var password_eye = $('#id_old_password').attr('type');
            if (password_eye == 'password'){
                $('#id_old_password').attr("type","text");
                $('#password_eye1').removeClass('fas fa-eye-slash');
                $('#password_eye1').addClass('fas fa-eye');
            }
            else{
                $('#id_old_password').attr("type","password");
                $('#password_eye1').removeClass('fas fa-eye');
                $('#password_eye1').addClass('fas fa-eye-slash');
            }
        });
        $('#password_see2').click(function(){
            var password_eye = $('#id_new_password1').attr('type');
            if (password_eye == 'password'){
                $('#id_new_password1').attr("type","text");
                $('#password_eye2').removeClass('fas fa-eye-slash');
                $('#password_eye2').addClass('fas fa-eye');
            }
            else{
                $('#id_new_password1').attr("type","password");
                $('#password_eye2').removeClass('fas fa-eye');
                $('#password_eye2').addClass('fas fa-eye-slash');
            }
        });
        $('#password_see3').click(function(){
            var password_eye = $('#id_new_password2').attr('type');
            if (password_eye == 'password'){
                $('#id_new_password2').attr("type","text");
                $('#password_eye3').removeClass('fas fa-eye-slash');
                $('#password_eye3').addClass('fas fa-eye');
            }
            else{
                $('#id_new_password2').attr("type","password");
                $('#password_eye3').removeClass('fas fa-eye');
                $('#password_eye3').addClass('fas fa-eye-slash');
            }
        });
    </script>
{% endblock %}

lost-and-found/accounts/templates/edit_profile.html
{% extends 'base_layout.html' %}

{% block title %}
    Lost & Found : แก้ไขโปรไฟล์
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class='my-5'> <b>แก้ไขโปรไฟล์ : {{ user.username }} <i class="fas fa-id-card-alt"></i></b> </h1>
        <form action="{% url 'edit_profile' %}" enctype="multipart/form-data" method='POST' >
        {% csrf_token %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-5">
                        {% if success %}
                            <div class="alert alert-success" role="alert">
                                <i class="fa fa-exclamation-circle mr-1"></i> {{ success }}
                            </div>
                        {% endif %}
                        <div class="form-row">
                            {% for each_form in form %}
                                <div class="form-group col-md-6 mb-4">
                                    <label for="{{ each_form.id_for_label }}"> {{ each_form.label }}</label>
                                    {{ each_form }}
                                    <small class='text-danger'> {{ each_form.errors.0 }} </small>
                                </div>
                            {% endfor %}
                            <div class="form-group col-md-6">
                                <label> คณะ </label>
                                <select name="faculty" class='form-control' id="id_faculty">
                                    {% for faculty in facultys %}
                                        {% if faculty != user.userprofile.faculty %}
                                            <option value="{{ faculty.id }}">{{ faculty }}</option>
                                        {% else %}
                                            <option selected value="{{ faculty.id }}"> {{ user.userprofile.faculty }} </option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group col-md-6 mb-5">
                                <label>รูปภาพ</label>
                                <div class="custom-file">
                                    <input type="file" class='custom-file-input' name='picture' id="avatar">
                                    <label class="custom-file-label" for="avatar">อัพโหลดไฟล์</label>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class='btn btn-primary'>แก้ไขโปรไฟล์</button>
                    </div>
                    <div class="col-lg-4">
                        <div class="card h-100 w-100 text-dark mycard">
                            <div class="wrapper">
                                <img class="card-img-top" src="{{ user.userprofile.avatar.url }}" id="avatar_preview">
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">
                                    <b id='username'> {{ user.username }} </b>
                                </h5>
                                <p class="card-text">
                                    <p>
                                        <span id='first_name'>{{ user.first_name }}</span>
                                        <span id='last_name'>{{ user.last_name }}</span>
                                    </p>
                                    <p>อีเมล์ : <span id='email'> {{ user.email }} </span></p>
                                </p>
                            </div>
                            <div class="container mb-3 ml-1">
                                <p class="card-text">
                                    <span class="badge badge-pill badge-success" id='faculty'>{{ user.userprofile.faculty }}</span>
                                </p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">
                                    <b>สมัครสมาชิกวันที่ : </b> {% now "d F Y" %}
                                    <br>
                                    <b>เวลา : </b> {% now "H:i" %}
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block script %}
<script>
    /* read URL function */
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#avatar_preview').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    /* Bind : picture (avatar) */
    $("#avatar").change(function () {
        readURL(this);
        var fileName = $(this).val().split('\\').pop();
        $(this).next('.custom-file-label').html(fileName);
    });

    /* Bind: first_name */
    $("#id_first_name").on('input', function () {
        var text = $("#id_first_name").val();
        $("#first_name").html(text);
    });

    /* Bind: last_name */
    $("#id_last_name").on('input', function () {
        var text = $("#id_last_name").val();
        $("#last_name").html(text);
    });

    /* Bind: email */
    $("#id_email").on('input', function () {
        var text = $("#id_email").val();
        $("#email").html(text);
    });

    /* Bind: faculty */
    $("#id_faculty").on('input', function () {
        var text = $("#id_faculty").find(":selected").text();
        $("#faculty").html(text);
    });
</script>
{% endblock %}

lost-and-found/accounts/templates/signup.html
{% extends 'base_layout.html' %}
{% load static %}

{% block title %}
    Lost & Found : สมัครสมาชิก
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class='my-5'> <b>สมัครสมาชิก <i class="fas fa-address-card"></i></b> </h1>
        <form method="POST" action="{% url 'signup' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-5">
                        <div class="form-row">
                            {% for each_form in form %}
                                {% if forloop.counter0 == 1 or forloop.counter0 == 2 %}
                                    <div class="form-group col-md-6 mb-4">
                                        <label for="{{ each_form.id_for_label }}"> {{ each_form.label }}</label>
                                        <div class="input-group">
                                            {{ each_form }}
                                            <div class="input-group-append" id='password_see{{ forloop.counter0 }}'
                                                style='cursor: pointer;'>
                                                <span class="input-group-text">
                                                    <i id='password-eye{{ forloop.counter0 }}' class="fas fa-eye-slash"></i>
                                                </span>
                                            </div>
                                        </div>
                                        <small class='text-danger'> {{ each_form.errors.0 }} </small>
                                    </div>
                                {% else %}
                                    <div class="form-group col-md-6 mb-4">
                                        <label for="{{ each_form.id_for_label }}"> {{ each_form.label }}</label>
                                        {{ each_form }}
                                        <small class='text-danger'> {{ each_form.errors.0 }} </small>
                                    </div>
                                {% endif %}
                                {% if forloop.counter0 == 0 %}
                                    <div class="form-group col-md-6"></div>
                                {% endif %}
                            {% endfor %}
                            <div class="form-group col-md-6">
                                <label> คณะ </label>
                                <select name="faculty" class='form-control' id="id_faculty">
                                    {% for faculty in facultys %}
                                        <option value="{{ faculty.id }}">{{ faculty }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group col-md-6 mb-5">
                                <label>รูปภาพ</label>
                                <div class="custom-file">
                                    <input type="file" class='custom-file-input' name='picture' id="avatar">
                                    <label class="custom-file-label" for="avatar">อัพโหลดรูปภาพ</label>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class='btn btn-primary'>สมัครสมาชิก</button>
                    </div>
                    <div class="col-lg-4">
                        <div class="card h-100 w-100 text-dark mycard">
                            <div class="wrapper">
                                <img class="card-img-top" src="{% static 'images/user_default.gif' %}" id="avatar_preview">
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">
                                    <b id='username'>ชื่อผู้ใช้งาน</b>
                                </h5>
                                <p class="card-text">
                                    <p>
                                        <span id='first_name'>ชื่อจริง</span>
                                        <span id='last_name'>นามสกุล</span>
                                    </p>
                                    <p>อีเมล์ : <span id='email'> example@example.com </span></p>
                                </p>
                            </div>
                            <div class="container mb-3 ml-1">
                                <p class="card-text">
                                    <span class="badge badge-pill badge-success" id='faculty'>เทคโนโลยีสารสนเทศ</span>
                                </p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">
                                    <b>สมัครสมาชิกวันที่ : </b> {% now "d F Y" %}
                                    <br>
                                    <b>เวลา : </b> {% now "H:i" %}
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block script %}
<script>
    /* read URL function */
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#avatar_preview').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    /* Bind : picture (avatar) */
    $("#avatar").change(function () {
        readURL(this);
        var fileName = $(this).val().split('\\').pop();
        $(this).next('.custom-file-label').html(fileName);
    });

    /* Bind: username */
    $("#id_username").on('input', function () {
        var text = $("#id_username").val();
        $("#username").html(text);
    });

    /* Bind: first_name */
    $("#id_first_name").on('input', function () {
        var text = $("#id_first_name").val();
        $("#first_name").html(text);
    });

    /* Bind: last_name */
    $("#id_last_name").on('input', function () {
        var text = $("#id_last_name").val();
        $("#last_name").html(text);
    });

    /* Bind: email */
    $("#id_email").on('input', function () {
        var text = $("#id_email").val();
        $("#email").html(text);
    });

    /* Bind: faculty */
    $("#id_faculty").on('input', function () {
        var text = $("#id_faculty").find(":selected").text();
        $("#faculty").html(text);
    });

    /* Password see button 1 */
    $('#password_see1').click(function () {
        var password_eye = $('#id_password1').attr('type');

        if (password_eye == 'password') {
            $('#id_password1').attr("type", "text");
            $('#password-eye1').removeClass('fas fa-eye-slash');
            $('#password-eye1').addClass('fas fa-eye');
        }
        else {
            $('#id_password1').attr("type", "password");
            $('#password-eye1').removeClass('fas fa-eye');
            $('#password-eye1').addClass('fas fa-eye-slash');
        }
    });

    /* Password see button 2 */
    $('#password_see2').click(function () {
        var password_eye = $('#id_password2').attr('type');

        if (password_eye == 'password') {
            $('#id_password2').attr("type", "text");
            $('#password-eye2').removeClass('fas fa-eye-slash');
            $('#password-eye2').addClass('fas fa-eye');
        }
        else {
            $('#id_password2').attr("type", "password");
            $('#password-eye2').removeClass('fas fa-eye');
            $('#password-eye2').addClass('fas fa-eye-slash');
        }
    });
</script>
{% endblock %}